### ISSUE TITLE
How to get all available wifi info?

### ISSUE THREAD

**Issue by Bharath-Kumar-S** [smaho-gmbh/android_wifi_info#3]
How to get information regarding all available wifi.

Please let me know how to achieve it.

**Comment by vincevargadev** [comment]
Do you mean getting all available WiFi networks that the mobile sees, even the ones that the phone is not connected to?

**Comment by Bharath-Kumar-S** [comment]
Yes @vargavince91 you are correct.

**Comment by Bharath-Kumar-S** [comment]
I need rssi value for each wifi to calculate distance between access point and Mobile device.

**Comment by vincevargadev** [comment]
This package cannot fetch all available WiFi networks' info. This package wraps the Android [`WifiInfo`](https://developer.android.com/reference/android/net/wifi/WifiInfo) class that describes the state of a Wifi connection that is active or is in the process of being set up. As such, this package does not include what you need.

If you want to fetch all "visible" networks, you would need to write the Android code yourself and pass that to the Flutter code (or find a package that does that). Something along these lines: https://stackoverflow.com/questions/18741034/how-to-get-available-wifi-networks-and-display-them-in-a-list-in-android
